---
extends: "airbnb"
ecmaFeatures:
  modules: true
env:
  es6: true
  browser: true
  node: true
globals:
  describe: true
  it: true
  beforeEach: true
rules:
  import/no-extraneous-dependencies: 0
  no-underscore-dangle: 0
